version: '3.9'

services:
  tinyurl:
    build:
      context: ./
      dockerfile: docker/tinyurl/Dockerfile
    restart: always
    environment:
      APP_PORT: ":8080"
      DEFAULT_URL_LEN: 10
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ""


  redis:
    hostname: redis
    build:
      context: ./
      dockerfile: docker/redis/Dockerfile
    restart: always
